# _config.yml
title: TIL by Sany
description: My learning journey - one day at a time
baseurl: "/til"
url: "https://sa-ny.github.io"
github_username: sa-ny

# Theme settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - serve.sh
  - setup-local.sh
  - README.md

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Collection settings
collections:
  tags:
    output: true
    permalink: /tags/:path/